### PR TITLE
Trying different ways to load page to update three states...

### PR DESCRIPTION
**Pull request by donuty**
Some notes... mostly for myself? 

So I redid the component i'm working on and tried to use Hooks.

Loving hooks!!!!

And some of my function that is meant to add objects to my related items data array is working.  But only adds one object, and then quits.

Also not sure how to implement useEffect to update state upon load without causing it to re-render repeatedly... think it's how I'm trying to set state in my quest to add data to the related items array...

Did make one call to help desk with limited success.  The SEIR was like what the heck is this, lol.

If anyone has any insights into how to approach this differently , I'd love to hear about it!  

You can observe the strange multiple re-rendering by uncommenting lines 77-87 in relatedProducts.jsx.

### CODE REVIEW

**Comment by sase6** [comment]
Hey, I remember Alex saying be careful with React Hooks since other students will be using our FEC code for their SDC and since it's not apart of the curriculum they might have a hard time. Other than that, the code in my opinion could be a litter more modularized like with the use of helper functions. i.e. set related products() is extremely long. It doesn't look bad and I can understand it, but i'd like for the other guys to check it out first.

**Comment by sase6** [comment]
Other than that, you're killing it!! lets goooo

**Review by drksthrd — COMMENTED** [review]
Yeah I agree with Sase, I don't think we're allowed to use hooks in FEC. Which is a shame, they seem to be what React developers use now.

**Comment by donuty** [comment]
Thank you for the feedback, y'all!  And I totally forgot about not using Hooks.   I'll rewrite with Class Components!

**Comment by donuty** [comment]
Closing pull request for now to refactor with Class Components.  :)

**Pull request closed without merging**
