### PR TITLE
Created a Rough Skeleton for Overview Image Gallery Component. 

### PR DESCRIPTION
**Pull request by DarianAltF4**
Additions I made:
- Added a Product Overview placeholder

- Added an Image Gallery placeholder which includes place holders for:
1. Default View
2. Selected Image
3. All Image Thumbnails Component
4. Single Image Thumbnail Component

- Added borders around each component so I could work on positioning them later.

### CODE REVIEW

**Comment by sase6** [comment]
Hey, I really liked the way you named the components. I was struggling with finding great folder/ component names. Anyways, the only thing I really wanna mention about the PR is the inline css. I think you may have it in as a placeholder but, the inline css will get very messy in my opinion, especially since its all we have (we cant use things like material ui). Other than that, great sutff! your racing everyone haha, someones having fun!!

**Comment by DarianAltF4** [comment]
Thank you for the review. I will add a CSS file to our repo, add className to each component and submit a new PR. 😁

**Comment by donuty** [comment]
This looks great @DarianAltF4 !  And good idea about moving the CSS up, @sase6.

**Comment by DarianAltF4** [comment]
Added edits that Sase recommended. Ready for another review. @sase6

**Review by sase6 — APPROVED** [review]
Looks great, really nice that you resolved that issue for everyone haha.

**Pull request merged**
